[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"

[build]
publish = "dist"
command = "scripts/install.sh && scripts/dev.sh"
