[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"

[build]
environment = { PYTHON_VERSION = "3.11" }
command = "jupyter lite build --contents content --output-dir dist"
publish = "dist"
